### ISSUE TITLE
Misspeling

### ISSUE THREAD

**Issue by gegen07** [jemaf/Slides-Android#1]
In Toolkit [Android-Ecosystem](https://github.com/jemaf/Slides-Android/blob/master/src/slides/02_android_ecosystem.html) it's written Andorid SDK instead of Android.

**Comment by jemaf** [comment]
Hi @gegen07 

The link provided in toolkit slide actually is correct, as it refers to the Android Development Kit (SDK).

In fact, both Andorid SDK and Android Studio redirects to the same page. Im gonna fix it to make it clear.

Thanks for your report!! :)
